uazapi:
  baseUrl: https://lucas.uazapi.com
  token: c8ce1ac8-3745-44a7-afba-e5dcc6e7ea74
  instanceId: r9b27e9e7933e0b
  adminToken: gPiH1n55i1Cw5zwv4c923XrHnnWIvubFrgjDwmHCoCmHcXlNH2
settings:
  timezone: America/Sao_Paulo
  delayBetweenMessages: 3000
  delayBetweenGroups: 5000
schedules:
  - name: Lembrete teste
    message: TESTE
    groups:
      - 120363424525439938@g.us
    cron: 32 9 * * 1,2,3,4,5
    stickerPath: ./config/stickers/atencao.webp
